### ISSUE TITLE
Add a 'Movie Details' Page

### ISSUE THREAD

**Issue by eleensmathew** [ContriHUB/MovieScreen#13]
### Expected behavior

Add a page that allows users to read the movie description and title on their own, with a list of movies displayed on the movie_list page. When a user clicks on a movie title, they should be taken to a separate movie_details page where all the details of the selected movie, such as the title, description, release date, runtime (if available), are displayed. Additionally, the cast information should be fetched from the OMDb API, which is already used in the add_movie view, and displayed on the movie_details page in a clear format. The cast should be presented as a list, with each actor's name displayed on a new line.
DON'T add movie ratings.
![image](https://github.com/user-attachments/assets/c5474903-061d-49f3-a4d5-1f9b498382df)

### Current behavior
Right now clicking on the movie in the movie_list doesn't take us to a new page.
![image](https://github.com/user-attachments/assets/7dca817b-dd8d-445c-b14c-5a730f954ded)

**Comment by ShouryaMishra2006** [comment]
@eleensmathew please assign me this issue

**Comment by eleensmathew** [comment]
Hey Let me add this issue in COntrihub and you can request assignment there

**Comment by samimshoaib01** [comment]
Please assign this issue if not assigned to anyone

**Comment by Vaishnavi1047** [comment]
![Screenshot 2024-10-12 192739](https://github.com/user-attachments/assets/6d58f0b2-205f-4a62-a181-187bb7268973)
@eleensmathew whats the issue

**Comment by eleensmathew** [comment]
There isnt any issue

**Comment by Vaishnavi1047** [comment]
@eleensmathew how to run it in ? i tried it is not running

**Comment by eleensmathew** [comment]
Check out the readme

**Comment by Vaishnavi1047** [comment]
I read it but like the virtual environment we have to deactivate after we are done with out work?

**Comment by eleensmathew** [comment]
Yes we have to deactivate

**Comment by Vaishnavi1047** [comment]
![Screenshot 2024-10-12 205724](https://github.com/user-attachments/assets/7da77e98-8e78-4966-bb86-397bd1a1b9b9)
@eleensmathew ?

**Comment by eleensmathew** [comment]
The path is wrong

**Comment by Vaishnavi1047** [comment]
it was giving in the running migration

**Comment by Vaishnavi1047** [comment]
sry got it ,it worked

**Comment by Vaishnavi1047** [comment]
![Screenshot 2024-10-12 210543](https://github.com/user-attachments/assets/2bc39885-19e8-4830-970a-7e792eb778d4)

**Comment by eleensmathew** [comment]
/user/shows/

**Comment by Vaishnavi1047** [comment]
![Screenshot 2024-10-12 211053](https://github.com/user-attachments/assets/85e642b1-4b64-4ce9-9d75-6f681d16fc53)
in these two pages i have to work on right?

**Comment by eleensmathew** [comment]
Yup

**Comment by Vaishnavi1047** [comment]
and what u mean by show here ? like movie list me we have to add movies also on clicking the movie it should take us to detail page then we donot have any use of show here na?

**Comment by eleensmathew** [comment]
So in a movie theater, a movie can have multiple show times right? So when someone purchase a movie to ket multiple times of the show are available. Also for each show we need to track which all seats are bought.

**Comment by Vaishnavi1047** [comment]
@eleensmathew i am not able to add the movies donot know why its saying to give email and enter password when i am going to /add_movies

**Comment by eleensmathew** [comment]
I think you should refer to the django documentation https://docs.djangoproject.com/en/5.1/

**Comment by Vaishnavi1047** [comment]
can u specify which part of the documentation should i read to solve my problem

**Comment by eleensmathew** [comment]
I think since you are facing a lot of issues getting an overview of the entire documentation would help.

**Comment by Vaishnavi1047** [comment]
hm okay mam as i am not enough comfortable in working it should be good thank you

**Comment by Vaishnavi1047** [comment]
@eleensmathew can u provide the api key as it wasnot mention in the docs 
![Screenshot 2024-10-12 225844](https://github.com/user-attachments/assets/f77b3ce8-09f0-4f71-9b44-72c9622aef2f)

**Comment by eleensmathew** [comment]
You will have to create your own :)

**Comment by Vaishnavi1047** [comment]
![Screenshot 2024-10-13 003648](https://github.com/user-attachments/assets/80460f86-4f29-47c1-b606-34a656b1ed78)
is it fine the list page ?

**Comment by Vaishnavi1047** [comment]
![Screenshot 2024-10-13 004818](https://github.com/user-attachments/assets/9570127e-b9f0-472d-a98e-89c5761c3fe9)
i am taking the ref from {
  "Search": [
    {
      "Title": "Maverick and Ariel's First Ever Ever Movie Hollywood or Else... (Ang pinakamahabang title ng movie sa balat ng lupa)",
      "Year": "2010",
      "imdbID": "tt1204784",
      "Type": "movie",
      "Poster": "N/A"
    },
    {
      "Title": "The Movie Title",
      "Year": "2017",
      "imdbID": "tt6730584",
      "Type": "movie",
      "Poster": "https://m.media-amazon.com/images/M/MV5BNTNiOWJjMjYtYWFlYS00OGFkLTlhMDktNjQ5ZGViYTYyMTY4XkEyXkFqcGdeQXVyNTkyNjA2MTQ@._V1_SX300.jpg"
    },
    {
      "Title": "What Is This Movie that Ian Is so Excited About It Makes No Sense Whatsoever and There Is No Way It's Going to Be Made without Him Knowing It - Da Best Title Ever Btw:) : The Movie",
      "Year": "2020",
      "imdbID": "tt14290026",
      "Type": "movie",
      "Poster": "https://m.media-amazon.com/images/M/MV5BNDMyNjlkOGEtOWFhZS00ZTlmLWJkNDQtNzQ3YjQ1ZTI5ZTg4XkEyXkFqcGc@._V1_SX300.jpg"
    }
  ],
  "totalResults": "3",
  "Response": "True"
} api call

**Comment by Vaishnavi1047** [comment]
@eleensmathew 
![Screenshot 2024-10-13 011903](https://github.com/user-attachments/assets/50cf4834-c5f8-4949-9f80-608a5f4fe647)
as in this api no cast is there so what to do i am using this information only in movie details mam

**Comment by eleensmathew** [comment]
> ![Screenshot 2024-10-13 003648](https://github.com/user-attachments/assets/80460f86-4f29-47c1-b606-34a656b1ed78)
> 
> is it fine the list page ?

Looks good but why have you changed the movie list page?

**Comment by eleensmathew** [comment]
> @eleensmathew 
> 
> ![Screenshot 2024-10-13 011903](https://github.com/user-attachments/assets/50cf4834-c5f8-4949-9f80-608a5f4fe647)
> 
> as in this api no cast is there so what to do i am using this information only in movie details mam

Hmm have you tried reading ondb docs if they have a certain api for this? Else what you can do is find another api provider to get the info.

**Comment by Vaishnavi1047** [comment]
@eleensmathew i have made the changes in model as per this now if searched for another api i have to again change the movies model

**Comment by eleensmathew** [comment]
Why does getting info from an api change your model? If you are done make a pr and I'll review your code and suggest changes.

**Comment by Vaishnavi1047** [comment]
@eleensmathew as model donot have omdb value to make every movie a unique giving it a id so i have added that which ensures on clicking u are going to details of a particular movie only

**Comment by eleensmathew** [comment]
Hey check this out https://github.com/pshrmn/notes/blob/master/django/models.md

**Comment by VishalMinj** [comment]
Is this issue open right now?

**Comment by eleensmathew** [comment]
Taken up by someone currently

**Comment by hexwhiz** [comment]
@eleensmathew I have made the PR.
