### ISSUE TITLE
Implement login and sign up

### ISSUE THREAD

**Issue by eleensmathew** [ContriHUB/MovieScreen#18]
### Expected behavior
Implement a login and sign up page for both users and admins. Add this page to the navbar if not signed in and add logout function if signed in.

### Current behavior
Right now only admins can purchase tickets after admin login. This should be changed so that any logged in user can purchase a ticket.

**Comment by VishalMinj** [comment]
Please assign this issue

**Comment by Rockyoudead8** [comment]
can you assign this issue to me as well

**Comment by divyanshu-912** [comment]
Assign this ton me

**Comment by eleensmathew** [comment]
Already assigned via contrihub website.

**Comment by VishalMinj** [comment]
A few queries 
- I can style the login/signup form?
- I've to use the base User for account creation?

**Comment by eleensmathew** [comment]
Yes and yes

**Comment by VishalMinj** [comment]
Sign up page for admin too?? 
Aren't admin accounts supposed to be created from the backend/terminal?

**Comment by eleensmathew** [comment]
No need for admin sign up

**Comment by VishalMinj** [comment]
Another thing is that the base class is User for both use and admin, so the admin can also use the user login page. So may be no dedicated page for admin, or do you want to restrict admin entering from regular login? 
Also can I toggle the design of navbar slightly?

**Comment by eleensmathew** [comment]
Dont restrict admin from regular admin. Feel free to toggle navbar design

**Comment by VishalMinj** [comment]
Hey @eleensmathew, here's  preview
![image](https://github.com/user-attachments/assets/094779d8-a199-489c-827e-01dc3ede8b9b)
![image](https://github.com/user-attachments/assets/fda7a332-f98c-4db5-8fc0-9e8519d1151d)
![image](https://github.com/user-attachments/assets/d8ed354c-bd65-4845-bc58-b5a968f93606)

**Comment by VishalMinj** [comment]
Also I don't see the url of ticket booking. There is the html for that and a url to carry the seat id I guess. But I don't see the url to open that page

**Comment by VishalMinj** [comment]
Add movie ain't working?

**Comment by eleensmathew** [comment]
Check urls.py for the url

**Comment by eleensmathew** [comment]
> Add movie ain't working?

Its based on an api - omdb. As the api key in a .env file and it will work.

**Comment by VishalMinj** [comment]
Ticket booking to be accessed from movie list or from another button on navbar?

**Comment by eleensmathew** [comment]
From showlist

**Comment by VishalMinj** [comment]
Okay, it seems to me that the logic for ticket booking is allready working. What do i have to do about it except?

**Comment by VishalMinj** [comment]
Ticket booking seems to be working for regular user. What do you wish to implement in it?

**Comment by eleensmathew** [comment]
Nothing. If you have implemented the login and sign up as well as the html css changes feel free to raise pr

**Comment by VishalMinj** [comment]
oh, ok let me make some final checks
