### ISSUE TITLE
Send emails after ticket purchase.

### ISSUE THREAD

**Issue by eleensmathew** [ContriHUB/MovieScreen#21]
### Expected behavior
After the user buys the ticket, send an email with the ticket details to the user. You may or may not need to change the models to include the email ID of users while signing up.

Make changes to the readme for replicating the steps for changing the email config to send emails.

### Current behavior
After the user buys the ticket, no email is sent for confirmation.

Attach screenshots of how you have tested the changes in your local system

**Comment by samimshoaib01** [comment]
I would like to work on this

**Comment by VishalMinj** [comment]
I'm done, Check if the instructions of read me are clear

![image](https://github.com/user-attachments/assets/662424b4-b865-451a-a682-ac7ebf14e301)

Here the email sample received 

![image](https://github.com/user-attachments/assets/aa9b08d8-a10a-4ba2-8b4c-e187cc12fa12)

Also I've not added any kind of email validation at the time of signup

**Comment by eleensmathew** [comment]
In the readme also attach the link of the source you referenced from. Then feel free to make the pr.
