### ISSUE TITLE
Adding movie Recommendation system

### ISSUE THREAD

**Issue by eleensmathew** [ContriHUB/MovieScreen#22]
### Expected behavior
Make a KNN-based movie recommendation system. DON'T integrate with the website. The User should input a movie and the system should output n similar movies based on the input. Make a separate Python file or Jupyter notebook (also feel free to make a google colab or kaggle notebook and attach a link to the pr and just add your name into the contributors.md ). Will give bonus points based on accuracy.  Attach screenshots in PR.

Feel free to ask doubts below if facing any confusion.

**Comment by Aryan10** [comment]
Please assign this to me. I need to only create the Jupyter notebook file right?

**Comment by eleensmathew** [comment]
> Please assign this to me. I need to only create the Jupyter notebook file right?

You are assigned and yes
