### ISSUE TITLE
Fetch details about the movie using an API

### ISSUE THREAD

**Issue by eleensmathew** [ContriHUB/MovieScreen#3]
### Current Behaviour
Right now, users have to manually enter the movie title, description, and movie image poster.

### Expected Behaviour
Based on user input of the title, save the description and image from a free web API.

![image](https://github.com/user-attachments/assets/6f52a8fa-0d36-4958-8289-159564d2efba)
It's very bad design I know

**Comment by DeshDeepakKushwaha** [comment]
can u assign this issue to me

**Comment by eleensmathew** [comment]
Assigned to divyashsingh101

**Comment by divyanshsingh101** [comment]
do i  have to make two form or if only title is entered i will fetch data from api else normal flow ?

**Comment by eleensmathew** [comment]
If you can implement an auto-complete on the title I will give you a lot of bonus points. Don't make two forms only if the correct title is entered and that title exists then populate those fields in db. You can modify the form so that the description and poster isn't asked in frontend.

**Comment by divyanshsingh101** [comment]
i need to push the code by 
Tomorrow morning ?

**Comment by divyanshsingh101** [comment]
i implemented if only title field is given then fetch data from api else take the user data
and do i need to segregate the shows and movie ?

**Comment by eleensmathew** [comment]
Wdym by segregate?

**Comment by divyanshsingh101** [comment]
like there are three sections show  add  and movie  if it is a show then we need to put it in the shows section else movie?

**Comment by divyanshsingh101** [comment]
![Screenshot 2024-10-08 235815](https://github.com/user-attachments/assets/49f6a35d-fd02-4034-b263-ce031455870d)

**Comment by eleensmathew** [comment]
You Dont need need to bother about show logic. If a movie is added it must be listed in movie list also check if the same movie is repeating or not before saving the movie in the db.

**Comment by divyanshsingh101** [comment]
![Screenshot 2024-10-09 112818](https://github.com/user-attachments/assets/24640053-a33f-47d2-a12c-bd4785b2d11f)
