### ISSUE TITLE
Make UI of the website consistent

### ISSUE THREAD

**Issue by eleensmathew** [ContriHUB/MovieScreen#37]
Right now each page has different styles and themes for every page. Make this consistent throughout.

**Comment by VishalMinj** [comment]
@eleensmathew here's the preview. Suggest if any tweaks needed or else I may proceed with updating readme and pr. 

![image](https://github.com/user-attachments/assets/79c1a456-b5c6-43d7-831f-32113252e940)
![image](https://github.com/user-attachments/assets/8cf4ec9f-db03-497d-9329-1caf2060ec22)
![image](https://github.com/user-attachments/assets/8c1a7f55-53bd-4ef3-8db9-7720331c6cdc)
![image](https://github.com/user-attachments/assets/4589334d-4bf0-4154-9123-38670d9c1147)
![image](https://github.com/user-attachments/assets/b1382258-812d-4efe-9d8b-1edd4974cab0)
![image](https://github.com/user-attachments/assets/52418e61-b721-4c8a-866b-5947d4ef1dcc)
![image](https://github.com/user-attachments/assets/aa951281-9edb-46b4-aef0-e9542f03869c)

**Comment by eleensmathew** [comment]
Also the book show ui. If you are short on c time you can submit the pr and modify later

**Comment by VishalMinj** [comment]
I'll look into it

**Comment by VishalMinj** [comment]
Here, take a look
![image](https://github.com/user-attachments/assets/ed35817f-34c2-4fee-b6bd-393b684b616c)
![image](https://github.com/user-attachments/assets/07983e87-40be-471d-9504-ff8a430aa5a0)

**Comment by eleensmathew** [comment]
Lgtm
