### ISSUE TITLE
Add functionlity for customers(users) to purchase show tickets.

### ISSUE THREAD

**Issue by eleensmathew** [ContriHUB/MovieScreen#4]
### Current behavior
Right now, the website only has functionality for admins to add movies. This website would be even more useful if it had functionality for customers to book shows by purchasing tickets.
### Expected behavior
Make changes to the models so that customers can book shows for only up to 2 maximum tickets per month. The database should also keep track of which seats (ex A1) are booked so that there is no confusion about the seats among customers.

**Comment by DeshDeepakKushwaha** [comment]
can u assign this task to me

**Comment by eleensmathew** [comment]
Assigned to samimshoaib01

**Comment by samimshoaib01** [comment]
Good evening ma'am,
sac site was down whole day yestereday , due to which i was not knowing that i got assigned this issue , i knew today morning. 
I got stuck in setting the project locally i guess
when i try to add movie by add_movie/ or through django i get this error 
 
![Screenshot from 2024-10-09 16-21-42](https://github.com/user-attachments/assets/661bd701-e857-4493-bf2c-f804f156cde3)

**Comment by eleensmathew** [comment]
read django docs about migrations. https://docs.djangoproject.com/en/5.1/topics/migrations/ also if that doesnt work try this (python manage.py migrate --run-syncdb)

**Comment by samimshoaib01** [comment]
Ma'am  is login required for booking a ticket ?

**Comment by eleensmathew** [comment]
Dont implememt login

**Comment by samimshoaib01** [comment]
Ma'am I was implementing using a login .. so i require only to update modals , urls.py or there is anything which I am missing

**Comment by eleensmathew** [comment]
If you have already implemented a login then feel free to push that code.

**Comment by eleensmathew** [comment]
Also you do have to write a view and change the html

**Comment by ShivaniSaini123** [comment]
I want to contribute to this issue. Has this issue already been assigned?
