### ISSUE TITLE
change frontend of the seat availbilty per show.

### ISSUE THREAD

**Issue by eleensmathew** [ContriHUB/MovieScreen#5]
### Expected behavior
Change the frontend of the seat visible for each show. When clicking on the show display which all seats are booked and which seats are empty.

### Current behavior
The website allows booking of seats but the display is not the best looking.

###Bonus 
Make the pages fun with cool css. Additionally, you can display messages like seats filling up fast or similar messages when the user clicks on the show page.

**Comment by DeshDeepakKushwaha** [comment]
Can you assign this issue to me

**Comment by eleensmathew** [comment]
This issue only becomes open after #4 is solved

**Comment by samimshoaib01** [comment]
is this issue assigned to someone ?

**Comment by sakshi-patil-1111** [comment]
thanks for assigning, working on this issue
