### ISSUE TITLE
Add ratings for movie

### ISSUE THREAD

**Issue by eleensmathew** [ContriHUB/MovieScreen#8]
Please choose your issue template from the following options:

### Expected behavior
Fetch current ratings for a movie from an external API (critics rating). Also, implement a feature where any user without any authentication can rate any movie in movie_list. It would be cool if the ratings were displayed as stars.
![image](https://github.com/user-attachments/assets/d9b67caa-0fd9-400d-abde-df1f98004b7f)
So under the movie, there must be 
1.a critics rating(fetched from api)
2. user ratings(entered by users on the website)

 
### Current behavior
In http://127.0.0.1:8000/user/movie_list/ Each movie does not have a rating displayed on the movie page or movie_list page.

**Comment by divyanshsingh101** [comment]
plz assign me

**Comment by eleensmathew** [comment]
Request assignment through the website. If its down wait a bit.

**Comment by divyanshsingh101** [comment]
ma'am website is working but the issues are not listed

**Comment by eleensmathew** [comment]
![image](https://github.com/user-attachments/assets/10871691-5ef8-45b1-8e73-cb7f3a1d9baf)

**Comment by samimshoaib01** [comment]
Is this issue assigned to someone ?

**Comment by priyanshi-1316** [comment]
ma'am please assign this issue to me if it has not been assigned till now i have been trying to request for the assignment through the website but its not working , i have worked on this kind of issue in the past.

**Comment by eleensmathew** [comment]
Its assigned to someone else currently

**Comment by sakshi-patil-1111** [comment]
thanks for assigning, working on this issue

**Comment by sakshi-patil-1111** [comment]
Pr submitted https://github.com/ContriHUB/MovieScreen/pull/27 kindly check
